GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/6968c2214d64f7edf84af7e1

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Cómo hacer una escapada romántica con éxito",
    "author": "Adrià Marcet",
    "url": "https://unaurlquesuenebien.com",
    "likes": 16
}

###
POST https://fullopenstack-part3-render-test.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Sample ID from VSCode REST Client",
    "number": "040-123456"
}

###
DELETE https://fullopenstack-part3-render-test.onrender.com/api/persons/9

###
DELETE http://localhost:3003/api/blogs/29